name: Manhunt
version: '1.0-SNAPSHOT' # Make sure version matches pom.xml if needed, e.g., 1.0-SNAPSHOT
main: com.clarkson.manhunt.Manhunt
api-version: '1.21'
# No 'commands:' section here for Paper plugins
